name: Deploy Streamlit Trip Planner to HF Spaces

on:
  push:
    branches:
      - main  # Runs on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Configure Git for HF push
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      # 5️⃣ Push to HF Space
      - name: Push to Hugging Face Space
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          # Add HF remote
          git remote add hf https://huggingface.co/spaces/Jayandhan/trip-planner
          
          # Force push to main branch on HF Space
          git push hf main --force
